# Generated by Django 4.1.3 on 2022-12-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='00000', max_length=50),
        ),
    ]
