# Generated by Django 4.1.3 on 2022-12-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0008_country_book_published_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address Entries'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': ' Countries'},
        ),
    ]
